### PR TITLE
Add jq to dependencies

### PR DESCRIPTION
**Pull request by matthewh86**
noticed that the scripts kept complaining about missing "jq" dependency

### CODE REVIEW

**Comment by ghost** [comment]
i have makes script for installing complete VPS. If possible to work with you ? i not a professional but my script is correct. bye

**Comment by matthewh86** [comment]
@Mellisen, what kind of script is it? can you upload to Github?

**Comment by ghost** [comment]
yes, tomorrow, i go to sleep (i’m french)

**Comment by ghost** [comment]
sorry
i post my script where ?

**Comment by ghost** [comment]
https://github.com/Mellisen/LinuxGSM-Docker/blob/patch-1/mellisen

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/Mellisen/LinuxGSM-Docker">Mellisen/LinuxGSM-Docker</a></strong></div><div>LinuxGSM-Docker - The Official LinuxGSM Docker image</div></blockquote>

**Pull request merged**
